/**
 * Shared category normalization utilities.
 * Used by Candidates page, AI Search, and any component displaying categories.
 */

// ── Exact match normalization map ──
const CATEGORY_NORMALIZE: Record<string, string> = {
  // Software & Development
  'software development': 'Software Engineering',
  'software engineer': 'Software Engineering',
  'software engineering': 'Software Engineering',
  'frontend web developer': 'Software Engineering',
  'front-end developer': 'Software Engineering',
  'frontend developer': 'Software Engineering',
  'front end developer': 'Software Engineering',
  'full-stack developer': 'Software Engineering',
  'full stack developer': 'Software Engineering',
  'fullstack developer': 'Software Engineering',
  'ui/ux developer': 'Software Engineering',
  'ui/ux designer & front-end developer': 'Software Engineering',
  'rpa developer': 'Software Engineering',
  'web developer': 'Software Engineering',
  'web development': 'Software Engineering',
  'backend developer': 'Software Engineering',
  'backend development': 'Software Engineering',
  'mobile developer': 'Software Engineering',
  'mobile development': 'Software Engineering',
  'mobile app developer': 'Software Engineering',
  'mobile app development': 'Software Engineering',
  'ios developer': 'Software Engineering',
  'android developer': 'Software Engineering',
  'devops engineer': 'Software Engineering',
  'devops': 'Software Engineering',
  'cloud engineer': 'Software Engineering',
  'site reliability engineer': 'Software Engineering',
  'sre': 'Software Engineering',
  'platform engineer': 'Software Engineering',
  'systems developer': 'Software Engineering',
  'applications developer': 'Software Engineering',
  'application developer': 'Software Engineering',
  'api developer': 'Software Engineering',
  'embedded systems': 'Software Engineering',
  'game developer': 'Software Engineering',
  'blockchain developer': 'Software Engineering',
  'developer': 'Software Engineering',
  'programmer': 'Software Engineering',
  'coding': 'Software Engineering',
  'it development': 'Software Engineering',
  'it/development': 'Software Engineering',
  'information technology/software': 'Software Engineering',
  'application packaging': 'Software Engineering',
  // Data & Analytics
  'data analyst': 'Data & Analytics',
  'data science': 'Data & Analytics',
  'data scientist': 'Data & Analytics',
  'data analysis': 'Data & Analytics',
  'data analysis/business intelligence': 'Data & Analytics',
  'data analyst/business intelligence': 'Data & Analytics',
  'data analytics': 'Data & Analytics',
  'data engineering': 'Data & Analytics',
  'data engineer': 'Data & Analytics',
  'machine learning': 'Data & Analytics',
  'machine learning engineer': 'Data & Analytics',
  'ml engineer': 'Data & Analytics',
  'ai engineer': 'Data & Analytics',
  'ai/ml': 'Data & Analytics',
  'artificial intelligence': 'Data & Analytics',
  'bioinformatics': 'Data & Analytics',
  'business intelligence': 'Data & Analytics',
  'bi analyst': 'Data & Analytics',
  'big data': 'Data & Analytics',
  'data & analytics': 'Data & Analytics',
  'research': 'Data & Analytics',
  'analyst': 'Data & Analytics',
  // IT & Systems
  'it': 'IT & Systems',
  'it support': 'IT & Systems',
  'it/automation': 'IT & Systems',
  'it automation': 'IT & Systems',
  'it administrator': 'IT & Systems',
  'it manager': 'IT & Systems',
  'it specialist': 'IT & Systems',
  'it services': 'IT & Systems',
  'it operations': 'IT & Systems',
  'it infrastructure': 'IT & Systems',
  'it engineer': 'IT & Systems',
  'it support & engineering': 'IT & Systems',
  'it/admin': 'IT & Systems',
  'it service management': 'IT & Systems',
  'it asset management': 'IT & Systems',
  'network engineering': 'IT & Systems',
  'network engineer': 'IT & Systems',
  'network administrator': 'IT & Systems',
  'system administrator': 'IT & Systems',
  'system admin': 'IT & Systems',
  'systems administrator': 'IT & Systems',
  'systems engineer': 'IT & Systems',
  'information technology': 'IT & Systems',
  'information security': 'IT & Systems',
  'cyber security': 'IT & Systems',
  'cybersecurity': 'IT & Systems',
  'security analyst': 'IT & Systems',
  'it & systems': 'IT & Systems',
  'cloud computing': 'IT & Systems',
  'database administrator': 'IT & Systems',
  'dba': 'IT & Systems',
  'erp': 'IT & Systems',
  'sap': 'IT & Systems',
  'help desk': 'IT & Systems',
  'technical support': 'IT & Systems',
  'desktop support': 'IT & Systems',
  // Engineering
  'engineering': 'Engineering',
  'mechanical engineering': 'Engineering',
  'mechanical engineer': 'Engineering',
  'electrical engineering': 'Engineering',
  'electrical engineer': 'Engineering',
  'civil engineering': 'Engineering',
  'civil engineer': 'Engineering',
  'petroleum engineer': 'Engineering',
  'petroleum engineering': 'Engineering',
  'chemical engineering': 'Engineering',
  'chemical engineer': 'Engineering',
  'structural engineer': 'Engineering',
  'structural engineering': 'Engineering',
  'industrial engineering': 'Engineering',
  'industrial engineer': 'Engineering',
  'manufacturing engineering': 'Engineering',
  'mep engineer': 'Engineering',
  'mep engineering': 'Engineering',
  'hvac engineer': 'Engineering',
  'hvac': 'Engineering',
  'aerospace engineering': 'Engineering',
  'environmental engineering': 'Engineering',
  'biomedical engineering': 'Engineering',
  'construction': 'Engineering',
  'construction management': 'Engineering',
  'architecture': 'Engineering',
  'architect': 'Engineering',
  'quantity surveyor': 'Engineering',
  'project engineer': 'Engineering',
  'site engineer': 'Engineering',
  'maintenance engineer': 'Engineering',
  'reliability engineer': 'Engineering',
  'piping engineer': 'Engineering',
  'instrumentation engineer': 'Engineering',
  'control systems engineer': 'Engineering',
  'drilling engineer': 'Engineering',
  'oil & gas': 'Engineering',
  'oil and gas': 'Engineering',
  'energy': 'Engineering',
  'power engineering': 'Engineering',
  'automotive engineering': 'Engineering',
  'robotics': 'Engineering',
  'telecommunications': 'Engineering',
  'telecom': 'Engineering',
  'mechatronics engineering': 'Engineering',
  'computer engineering': 'Engineering',
  'facilities engineering': 'Engineering',
  'it/elv project engineer': 'Engineering',
  // HR & Admin
  'hr/admin': 'HR & Admin',
  'hr': 'HR & Admin',
  'human resources': 'HR & Admin',
  'administration': 'HR & Admin',
  'talent acquisition': 'HR & Admin',
  'recruitment': 'HR & Admin',
  'hr executive': 'HR & Admin',
  'hr admin support': 'HR & Admin',
  'hr admin': 'HR & Admin',
  'payroll/hr': 'HR & Admin',
  'payroll': 'HR & Admin',
  'admin/associate': 'HR & Admin',
  'admin executive': 'HR & Admin',
  'executive assistant': 'HR & Admin',
  'office manager': 'HR & Admin',
  'admin': 'HR & Admin',
  'administrative assistant': 'HR & Admin',
  'receptionist': 'HR & Admin',
  // Finance & Accounting
  'finance': 'Finance & Accounting',
  'accounting': 'Finance & Accounting',
  'accounting/finance': 'Finance & Accounting',
  'financial services': 'Finance & Accounting',
  'audit': 'Finance & Accounting',
  'banking': 'Finance & Accounting',
  'accountant': 'Finance & Accounting',
  'compliance': 'Finance & Accounting',
  'financial crime prevention/regulation': 'Finance & Accounting',
  'financial crime prevention/regulat': 'Finance & Accounting',
  'financial analyst': 'Finance & Accounting',
  'tax': 'Finance & Accounting',
  'treasury': 'Finance & Accounting',
  // Sales
  'sales': 'Sales',
  'business development': 'Sales',
  'account management': 'Sales',
  'real estate': 'Sales',
  // Operations & Management
  'operations': 'Operations',
  'supply chain management': 'Operations',
  'logistics': 'Operations',
  'procurement': 'Operations',
  'facilities management': 'Operations',
  'security & surveillance': 'Operations',
  'security management': 'Operations',
  'management': 'Operations',
  'executive management': 'Operations',
  // Project Management
  'project management': 'Project Management',
  'project manager': 'Project Management',
  'product management': 'Project Management',
  'scrum master': 'Project Management',
  // Consulting
  'consulting': 'Consulting',
  'management consulting': 'Consulting',
  // Healthcare
  'healthcare': 'Healthcare',
  'medical': 'Healthcare',
  'nursing': 'Healthcare',
  'hospital front office executive': 'Healthcare',
  'counseling and coordination': 'Healthcare',
  'counselling': 'Healthcare',
  'pharmacy': 'Healthcare',
  'physiotherapy': 'Healthcare',
  // Design & Creative
  'design': 'Design & Creative',
  'graphic design': 'Design & Creative',
  'ui/ux': 'Design & Creative',
  'design & creative': 'Design & Creative',
  'interior design': 'Design & Creative',
  // QA & Testing
  'quality assurance': 'QA & Testing',
  'qa': 'QA & Testing',
  'quality control': 'QA & Testing',
  // Marketing & Content
  'marketing': 'Marketing',
  'digital marketing': 'Marketing',
  'social media': 'Marketing',
  'public relations': 'Marketing',
  'content & communications': 'Marketing',
  'content & communication': 'Marketing',
  'content marketing': 'Marketing',
  'communications': 'Marketing',
  'content creator': 'Marketing',
  'copywriter': 'Marketing',
  'copywriting': 'Marketing',
  // Customer Service
  'customer service': 'Customer Service',
  'customer support': 'Customer Service',
  // Insurance & Safety
  'insurance': 'Insurance & Safety',
  'safety': 'Insurance & Safety',
  'insurance & safety': 'Insurance & Safety',
  'sr.hse officer': 'Insurance & Safety',
  'hse officer': 'Insurance & Safety',
  'hse': 'Insurance & Safety',
  'health and safety': 'Insurance & Safety',
  'occupational health': 'Insurance & Safety',
  // Retail & Hospitality
  'retail': 'Retail & Hospitality',
  'hospitality': 'Retail & Hospitality',
  'retail & hospitality': 'Retail & Hospitality',
  'food service': 'Retail & Hospitality',
  'hotel management': 'Retail & Hospitality',
  'restaurant': 'Retail & Hospitality',
  'food & beverage': 'Retail & Hospitality',
  'tourism': 'Retail & Hospitality',
  // Education & Training
  'education': 'Education',
  'teaching': 'Education',
  'instructor analyst': 'Education',
  'instructor': 'Education',
  'training': 'Education',
  'academic': 'Education',
  'professor': 'Education',
  'tutor': 'Education',
  // Legal
  'legal': 'Legal',
  'lawyer': 'Legal',
  // Business Analyst
  'business analyst': 'Business Analyst',
  'business analysis': 'Business Analyst',
  // General / catch-all
  'general': 'General',
  'insufficient data': 'General',
  'other': 'General',
  'not specified': 'General',
  'n/a': 'General',
  'professional': 'General',
  'general professional': 'General',
  'freelancer / contractor': 'General',
  'freelancer/contractor': 'General',
  'intern / trainee': 'General',
  'intern/trainee': 'General',
}

// ── Contains-based fuzzy fallback patterns ──
// Order matters: more specific patterns first
const CATEGORY_CONTAINS: [string, string][] = [
  // Software / Dev — specific first
  ['mobile app dev', 'Software Engineering'],
  ['application packag', 'Software Engineering'],
  ['software', 'Software Engineering'],
  ['developer', 'Software Engineering'],
  ['full stack', 'Software Engineering'],
  ['full-stack', 'Software Engineering'],
  ['devops', 'Software Engineering'],
  // Data & Analytics
  ['data scien', 'Data & Analytics'],
  ['data analy', 'Data & Analytics'],
  ['data engineer', 'Data & Analytics'],
  ['machine learning', 'Data & Analytics'],
  ['business intelligence', 'Data & Analytics'],
  ['research', 'Data & Analytics'],
  // IT & Systems — specific patterns
  ['it support', 'IT & Systems'],
  ['it service', 'IT & Systems'],
  ['it asset', 'IT & Systems'],
  ['it engineer', 'IT & Systems'],
  ['it automat', 'IT & Systems'],
  ['it/admin', 'IT & Systems'],
  ['it/elv', 'Engineering'],
  ['network', 'IT & Systems'],
  ['system admin', 'IT & Systems'],
  ['cyber', 'IT & Systems'],
  ['information technology', 'IT & Systems'],
  // Engineering
  ['mechatronics', 'Engineering'],
  ['computer engineer', 'Engineering'],
  ['facilities engineer', 'Engineering'],
  ['mechanical', 'Engineering'],
  ['electrical', 'Engineering'],
  ['civil', 'Engineering'],
  ['petroleum', 'Engineering'],
  ['structural', 'Engineering'],
  ['mep', 'Engineering'],
  ['construction', 'Engineering'],
  ['telecom', 'Engineering'],
  // HR & Admin
  ['human resource', 'HR & Admin'],
  ['talent acqui', 'HR & Admin'],
  ['recruit', 'HR & Admin'],
  ['payroll', 'HR & Admin'],
  ['hr admin', 'HR & Admin'],
  ['hr exec', 'HR & Admin'],
  ['admin exec', 'HR & Admin'],
  ['executive assistant', 'HR & Admin'],
  ['office manager', 'HR & Admin'],
  ['admin/assoc', 'HR & Admin'],
  ['administrat', 'HR & Admin'],
  // Finance & Accounting
  ['accountant', 'Finance & Accounting'],
  ['accounting', 'Finance & Accounting'],
  ['finance', 'Finance & Accounting'],
  ['financial crime', 'Finance & Accounting'],
  ['compliance', 'Finance & Accounting'],
  ['audit', 'Finance & Accounting'],
  ['banking', 'Finance & Accounting'],
  // Sales
  ['sales', 'Sales'],
  ['business develop', 'Sales'],
  ['account manag', 'Sales'],
  // Operations & Management
  ['supply chain', 'Operations'],
  ['logistics', 'Operations'],
  ['warehouse', 'Operations'],
  ['procurement', 'Operations'],
  ['facilities manag', 'Operations'],
  ['security manage', 'Operations'],
  ['security & surv', 'Operations'],
  ['executive manage', 'Operations'],
  ['operations', 'Operations'],
  // Project Management
  ['project manag', 'Project Management'],
  ['program manag', 'Project Management'],
  ['product manag', 'Project Management'],
  ['scrum', 'Project Management'],
  // Consulting
  ['consult', 'Consulting'],
  // Healthcare
  ['healthcare', 'Healthcare'],
  ['medical', 'Healthcare'],
  ['nurs', 'Healthcare'],
  ['pharma', 'Healthcare'],
  ['hospital', 'Healthcare'],
  ['counseling', 'Healthcare'],
  ['counselling', 'Healthcare'],
  // Design & Creative
  ['design', 'Design & Creative'],
  ['graphic', 'Design & Creative'],
  ['creative', 'Design & Creative'],
  ['ui/ux', 'Design & Creative'],
  // QA & Testing
  ['quality assur', 'QA & Testing'],
  ['quality control', 'QA & Testing'],
  ['testing', 'QA & Testing'],
  // Marketing & Content
  ['marketing', 'Marketing'],
  ['social media', 'Marketing'],
  ['content writ', 'Marketing'],
  ['public relation', 'Marketing'],
  ['content & comm', 'Marketing'],
  ['communicat', 'Marketing'],
  ['copywrite', 'Marketing'],
  // Customer Service
  ['customer serv', 'Customer Service'],
  ['customer supp', 'Customer Service'],
  ['call center', 'Customer Service'],
  // Insurance & Safety
  ['hse', 'Insurance & Safety'],
  ['insurance', 'Insurance & Safety'],
  ['safety', 'Insurance & Safety'],
  // Retail & Hospitality
  ['retail', 'Retail & Hospitality'],
  ['hospitality', 'Retail & Hospitality'],
  ['hotel', 'Retail & Hospitality'],
  ['food service', 'Retail & Hospitality'],
  ['food & bev', 'Retail & Hospitality'],
  ['restaurant', 'Retail & Hospitality'],
  // Education & Training
  ['instructor', 'Education'],
  ['education', 'Education'],
  ['teaching', 'Education'],
  ['training', 'Education'],
  // Legal
  ['legal', 'Legal'],
  ['lawyer', 'Legal'],
  // Business Analyst
  ['business analy', 'Business Analyst'],
]

/**
 * Normalize a raw category string to a canonical category name.
 * Uses exact match first, then contains-based fuzzy matching.
 */
export function normalizeCategory(raw: string): string {
  if (!raw) return 'General'
  const key = raw.toLowerCase().trim()
  if (CATEGORY_NORMALIZE[key]) return CATEGORY_NORMALIZE[key]
  for (const [pattern, category] of CATEGORY_CONTAINS) {
    if (key.includes(pattern)) return category
  }
  return raw
}
