/**
 * Shared category normalization utilities.
 * Used by Candidates page, AI Search, and any component displaying categories.
 */

// ── Exact match normalization map ──
const CATEGORY_NORMALIZE: Record<string, string> = {
  // Software & Development
  'software development': 'Software Engineering',
  'software engineer': 'Software Engineering',
  'software engineering': 'Software Engineering',
  'frontend web developer': 'Software Engineering',
  'front-end developer': 'Software Engineering',
  'frontend developer': 'Software Engineering',
  'front end developer': 'Software Engineering',
  'full-stack developer': 'Software Engineering',
  'full stack developer': 'Software Engineering',
  'fullstack developer': 'Software Engineering',
  'ui/ux developer': 'Software Engineering',
  'ui/ux designer & front-end developer': 'Software Engineering',
  'rpa developer': 'Software Engineering',
  'web developer': 'Software Engineering',
  'web development': 'Software Engineering',
  'backend developer': 'Software Engineering',
  'backend development': 'Software Engineering',
  'mobile developer': 'Software Engineering',
  'mobile development': 'Software Engineering',
  'mobile app developer': 'Software Engineering',
  'ios developer': 'Software Engineering',
  'android developer': 'Software Engineering',
  'devops engineer': 'Software Engineering',
  'devops': 'Software Engineering',
  'cloud engineer': 'Software Engineering',
  'site reliability engineer': 'Software Engineering',
  'sre': 'Software Engineering',
  'platform engineer': 'Software Engineering',
  'systems developer': 'Software Engineering',
  'applications developer': 'Software Engineering',
  'application developer': 'Software Engineering',
  'api developer': 'Software Engineering',
  'embedded systems': 'Software Engineering',
  'game developer': 'Software Engineering',
  'blockchain developer': 'Software Engineering',
  'developer': 'Software Engineering',
  'programmer': 'Software Engineering',
  'coding': 'Software Engineering',
  'it development': 'Software Engineering',
  'it/development': 'Software Engineering',
  'information technology/software': 'Software Engineering',
  // Data & Analytics
  'data analyst': 'Data & Analytics',
  'data science': 'Data & Analytics',
  'data scientist': 'Data & Analytics',
  'data analysis': 'Data & Analytics',
  'data analysis/business intelligence': 'Data & Analytics',
  'data analyst/business intelligence': 'Data & Analytics',
  'data analytics': 'Data & Analytics',
  'data engineering': 'Data & Analytics',
  'data engineer': 'Data & Analytics',
  'machine learning': 'Data & Analytics',
  'machine learning engineer': 'Data & Analytics',
  'ml engineer': 'Data & Analytics',
  'ai engineer': 'Data & Analytics',
  'ai/ml': 'Data & Analytics',
  'artificial intelligence': 'Data & Analytics',
  'bioinformatics': 'Data & Analytics',
  'business intelligence': 'Data & Analytics',
  'bi analyst': 'Data & Analytics',
  'big data': 'Data & Analytics',
  'data & analytics': 'Data & Analytics',
  // IT & Systems
  'it': 'IT & Systems',
  'it support': 'IT & Systems',
  'it/automation': 'IT & Systems',
  'it administrator': 'IT & Systems',
  'it manager': 'IT & Systems',
  'it specialist': 'IT & Systems',
  'it services': 'IT & Systems',
  'it operations': 'IT & Systems',
  'it infrastructure': 'IT & Systems',
  'network engineering': 'IT & Systems',
  'network engineer': 'IT & Systems',
  'network administrator': 'IT & Systems',
  'system administrator': 'IT & Systems',
  'system admin': 'IT & Systems',
  'systems administrator': 'IT & Systems',
  'systems engineer': 'IT & Systems',
  'information technology': 'IT & Systems',
  'information security': 'IT & Systems',
  'cyber security': 'IT & Systems',
  'cybersecurity': 'IT & Systems',
  'security analyst': 'IT & Systems',
  'it & systems': 'IT & Systems',
  'cloud computing': 'IT & Systems',
  'database administrator': 'IT & Systems',
  'dba': 'IT & Systems',
  'erp': 'IT & Systems',
  'sap': 'IT & Systems',
  'help desk': 'IT & Systems',
  'technical support': 'IT & Systems',
  'desktop support': 'IT & Systems',
  // Engineering
  'engineering': 'Engineering',
  'mechanical engineering': 'Engineering',
  'mechanical engineer': 'Engineering',
  'electrical engineering': 'Engineering',
  'electrical engineer': 'Engineering',
  'civil engineering': 'Engineering',
  'civil engineer': 'Engineering',
  'petroleum engineer': 'Engineering',
  'petroleum engineering': 'Engineering',
  'chemical engineering': 'Engineering',
  'chemical engineer': 'Engineering',
  'structural engineer': 'Engineering',
  'structural engineering': 'Engineering',
  'industrial engineering': 'Engineering',
  'industrial engineer': 'Engineering',
  'manufacturing engineering': 'Engineering',
  'mep engineer': 'Engineering',
  'mep engineering': 'Engineering',
  'hvac engineer': 'Engineering',
  'hvac': 'Engineering',
  'aerospace engineering': 'Engineering',
  'environmental engineering': 'Engineering',
  'biomedical engineering': 'Engineering',
  'construction': 'Engineering',
  'construction management': 'Engineering',
  'architecture': 'Engineering',
  'architect': 'Engineering',
  'quantity surveyor': 'Engineering',
  'project engineer': 'Engineering',
  'site engineer': 'Engineering',
  'maintenance engineer': 'Engineering',
  'reliability engineer': 'Engineering',
  'piping engineer': 'Engineering',
  'instrumentation engineer': 'Engineering',
  'control systems engineer': 'Engineering',
  'drilling engineer': 'Engineering',
  'oil & gas': 'Engineering',
  'oil and gas': 'Engineering',
  'energy': 'Engineering',
  'power engineering': 'Engineering',
  'automotive engineering': 'Engineering',
  'robotics': 'Engineering',
  'telecommunications': 'Engineering',
  'telecom': 'Engineering',
  // More categories...
  'hr/admin': 'HR & Admin',
  'hr': 'HR & Admin',
  'human resources': 'HR & Admin',
  'administration': 'HR & Admin',
  'talent acquisition': 'HR & Admin',
  'recruitment': 'HR & Admin',
  'finance': 'Finance & Accounting',
  'accounting': 'Finance & Accounting',
  'accounting/finance': 'Finance & Accounting',
  'financial services': 'Finance & Accounting',
  'audit': 'Finance & Accounting',
  'banking': 'Finance & Accounting',
  'sales': 'Sales',
  'business development': 'Sales',
  'account management': 'Sales',
  'real estate': 'Sales',
  'operations': 'Operations',
  'supply chain management': 'Operations',
  'logistics': 'Operations',
  'procurement': 'Operations',
  'project management': 'Project Management',
  'project manager': 'Project Management',
  'product management': 'Project Management',
  'scrum master': 'Project Management',
  'consulting': 'Consulting',
  'management consulting': 'Consulting',
  'healthcare': 'Healthcare',
  'medical': 'Healthcare',
  'nursing': 'Healthcare',
  'design': 'Design & Creative',
  'graphic design': 'Design & Creative',
  'ui/ux': 'Design & Creative',
  'quality assurance': 'QA & Testing',
  'qa': 'QA & Testing',
  'quality control': 'QA & Testing',
  'marketing': 'Marketing',
  'digital marketing': 'Marketing',
  'social media': 'Marketing',
  'public relations': 'Marketing',
  'customer service': 'Customer Service',
  'customer support': 'Customer Service',
  'insurance': 'Insurance & Safety',
  'safety': 'Insurance & Safety',
  'retail': 'Retail & Hospitality',
  'hospitality': 'Retail & Hospitality',
  'education': 'Education',
  'teaching': 'Education',
  'legal': 'Legal',
  'lawyer': 'Legal',
  'business analyst': 'Business Analyst',
  'business analysis': 'Business Analyst',
  'general': 'General',
  'insufficient data': 'General',
  'other': 'General',
  'not specified': 'General',
  'n/a': 'General',
  'unknown': 'General',
}

// ── Contains-based fuzzy fallback patterns ──
const CATEGORY_CONTAINS: [string, string][] = [
  ['software', 'Software Engineering'],
  ['developer', 'Software Engineering'],
  ['full stack', 'Software Engineering'],
  ['full-stack', 'Software Engineering'],
  ['devops', 'Software Engineering'],
  ['data scien', 'Data & Analytics'],
  ['data analy', 'Data & Analytics'],
  ['data engineer', 'Data & Analytics'],
  ['machine learning', 'Data & Analytics'],
  ['business intelligence', 'Data & Analytics'],
  ['network', 'IT & Systems'],
  ['system admin', 'IT & Systems'],
  ['cyber', 'IT & Systems'],
  ['information technology', 'IT & Systems'],
  ['mechanical', 'Engineering'],
  ['electrical', 'Engineering'],
  ['civil', 'Engineering'],
  ['petroleum', 'Engineering'],
  ['structural', 'Engineering'],
  ['mep', 'Engineering'],
  ['construction', 'Engineering'],
  ['human resource', 'HR & Admin'],
  ['talent acqui', 'HR & Admin'],
  ['recruit', 'HR & Admin'],
  ['administrat', 'HR & Admin'],
  ['accounting', 'Finance & Accounting'],
  ['finance', 'Finance & Accounting'],
  ['audit', 'Finance & Accounting'],
  ['banking', 'Finance & Accounting'],
  ['sales', 'Sales'],
  ['business develop', 'Sales'],
  ['account manag', 'Sales'],
  ['supply chain', 'Operations'],
  ['logistics', 'Operations'],
  ['warehouse', 'Operations'],
  ['procurement', 'Operations'],
  ['operations', 'Operations'],
  ['project manag', 'Project Management'],
  ['program manag', 'Project Management'],
  ['product manag', 'Project Management'],
  ['scrum', 'Project Management'],
  ['consult', 'Consulting'],
  ['healthcare', 'Healthcare'],
  ['medical', 'Healthcare'],
  ['nurs', 'Healthcare'],
  ['pharma', 'Healthcare'],
  ['design', 'Design & Creative'],
  ['graphic', 'Design & Creative'],
  ['creative', 'Design & Creative'],
  ['ui/ux', 'Design & Creative'],
  ['quality assur', 'QA & Testing'],
  ['quality control', 'QA & Testing'],
  ['testing', 'QA & Testing'],
  ['marketing', 'Marketing'],
  ['social media', 'Marketing'],
  ['content writ', 'Marketing'],
  ['public relation', 'Marketing'],
  ['customer serv', 'Customer Service'],
  ['customer supp', 'Customer Service'],
  ['call center', 'Customer Service'],
  ['insurance', 'Insurance & Safety'],
  ['safety', 'Insurance & Safety'],
  ['retail', 'Retail & Hospitality'],
  ['hospitality', 'Retail & Hospitality'],
  ['hotel', 'Retail & Hospitality'],
  ['education', 'Education'],
  ['teaching', 'Education'],
  ['training', 'Education'],
  ['legal', 'Legal'],
  ['lawyer', 'Legal'],
  ['business analy', 'Business Analyst'],
]

/**
 * Normalize a raw category string to a canonical category name.
 * Uses exact match first, then contains-based fuzzy matching.
 */
export function normalizeCategory(raw: string): string {
  if (!raw) return 'General'
  const key = raw.toLowerCase().trim()
  if (CATEGORY_NORMALIZE[key]) return CATEGORY_NORMALIZE[key]
  for (const [pattern, category] of CATEGORY_CONTAINS) {
    if (key.includes(pattern)) return category
  }
  return raw
}
